
spring:
  datasource:
    #   数据源基本配置
    username: root
    password: qm13418093703.
    driver-class-name: com.mysql.cj.jdbc.Driver
    #jdbc:mysql://127.0.0.1:3306/mybatis_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #jdbc:mysql://localhost:3306/ssm_crud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/javaprj_9?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true


mybatis-plus:
  configuration:
    #是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper所对应的XML文件位置）
  mapper-locations: classpath:mapper/*.xml
#    # 以下配置均有默认值,可以不设置
#    global-config:
#      db-config:
#        #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
#        id-type: auto
#        #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
#        field-strategy: NOT_EMPTY
#        #数据库类型
#        db-type: MYSQL
server:
  port: 8088
